AllCops:
  RunRailsCops: false

Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

SymbolArray:
  Description: 'Use %i or %I for arrays of symbols.'
  Enabled: true

LineLength:
  Description: 'Limit lines to 120 characters.'
  Max: 120
